🐕🐕🐕🐕🐕
kelseyhightower/nocode pull request #1295
Opened 2018-02-09 19:54 UTC by stella3d

2018-02-09 21:47 UTC, aidangomez requested changes
Looks good, one fix.

2018-02-09 21:47 UTC, aidangomez commented on dogsupport
> +
Extraneous, please remove.

2018-02-09 22:35 UTC, montera82 commented on dogsupport
> +
👍

2018-02-10 15:27 UTC, renannprado commented
Looks bad to me.
Please do not merge asap, I don't need this functionality either.

2024-08-05 22:53 UTC, closed without merging