Update README.md
kelseyhightower/nocode pull request #21
Opened 2018-02-07 00:31 UTC by iennae

Resolves Issue #17.

2018-02-07 02:15 UTC, lattwood requested changes
Referring to another file is code

2018-02-07 16:55 UTC, marcosalles requested changes

2018-02-07 16:55 UTC, marcosalles commented on README.md
> +Refer to [Contributing](https://github.com/kelseyhightower/nocode/blob/master/CONTRIBUTING.md) for the most up-to-date process.
is code, please remove

2018-10-17 03:26 UTC, closed without merging

2023-03-10 12:48 UTC, got991 commented on README.md
> +Refer to [Contributing](https://github.com/kelseyhightower/nocode/blob/master/CONTRIBUTING.md) for the most up-to-date process.
LOL

2023-03-10 12:48 UTC, got991 commented on README.md
> +Refer to [Contributing](https://github.com/kelseyhightower/nocode/blob/master/CONTRIBUTING.md) for the most up-to-date process.
> is markdown code, please remove

LOL.