Implement Unit Testing
kelseyhightower/nocode pull request #3925
Opened 2020-03-06 16:27 UTC by Escalion

As per the operating norm of organisations worldwide, no code was missing unit testing.
This commit includes a fully automated unit testing library for use with no code.

2020-03-07 00:44 UTC, martinfrancois approved these changes
LGTM

2020-06-17 21:15 UTC, b96m requested changes
Could you please add a unit test for your changes please? Otherwise LGTM, thanks

2020-06-17 21:29 UTC, Escalion commented
@bmoe24x as per the documentation the unit tests are automatically inferred from the code, thus this task is already complete :)

2020-06-17 21:38 UTC, bmoe24x commented
> @bmoe24x as per the documentation the unit tests are automatically inferred from the code, thus this task is already complete :)

surely your break this extensive codebase, we need to run integration, end to end, user acceptance, regression, and manual tests.

2020-07-03 00:23 UTC, conrad760 approved these changes

2020-07-03 03:08 UTC, anggit97 approved these changes
its clean

2020-07-03 03:08 UTC, anggit97 commented on README.md
> +Simple, right?
we need more code here, so others can contribute to make better unit test for this project

2020-07-07 11:23 UTC, Escalion commented on README.md
> +Simple, right?
Like this?
```
 
```

2020-10-20 22:34 UTC, TheMisir approved these changes
LGTM

2023-10-17 02:50 UTC, conrad760 commented
whats the status on this?

2026-02-05 12:05 UTC, Escalion commented
Closing because this is sitting in my to-do's perpetually

2026-02-05 12:05 UTC, closed without merging