‎
kelseyhightower/nocode pull request #5001
Opened 2022-12-13 21:24 UTC by ReddixT

‎

2022-12-13 21:25 UTC, theArgex commented
closes #5000

2023-01-07 18:41 UTC, MBRjun reviewed
🤣

2023-01-16 02:59 UTC, snproj commented
​

2023-01-16 20:09 UTC, Syrent commented
​

2023-01-19 19:10 UTC, MushyToast commented
You should probably edit the code so the performance is improved. Instead of this line, that eats up system resources:
`‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ `
Do this: 
`‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ `

2023-01-19 22:56 UTC, figadore requested changes
```

```

2023-08-22 11:20 UTC, shikukuya commented
​

2023-09-15 04:33 UTC, terryyyz commented
```

```

2023-09-15 04:34 UTC, terryyyz requested changes

2023-09-15 04:34 UTC, terryyyz commented on README.md
> -# No Code
```
```

2023-10-18 11:56 UTC, closed without merging